name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: extractions/setup-just@v2

      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal

      - name: install elan
        run: |
            set -o pipefail
            curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-aarch64-apple-darwin.tar.gz | tar xz
            ./elan-init -y --no-modify-path --default-toolchain none
            echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - name: query clang
        run: clang --version

      - uses: actions/checkout@v4

      - name: fetch mathlib cache
        run: lake exe cache get

      - name: build project
        run: just build

      - name: create release tarball
        run: |
          tar zcf raylean_macos-aarch64.tar.gz -C .lake/build/bin raylean

      - uses: actions/upload-artifact@v4
        with:
          name: macos-aarch64-binary
          path: raylean_macos-aarch64.tar.gz
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: extractions/setup-just@v2

      - name: Setup Rust
        run: rustup toolchain install stable --profile minimal

      - name: Install raylib deps
        run: sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev

      - name: install elan
        run: |
            set -o pipefail
            curl -sSfL https://github.com/leanprover/elan/releases/download/v3.1.1/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
            ./elan-init -y --no-modify-path --default-toolchain none
            echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: fetch mathlib cache
        run: lake exe cache get

      - name: build project
        run: just build

      - name: create release tarball
        run: |
          tar zcf raylean_linux-x86_64.tar.gz -C .lake/build/bin raylean

      - uses: actions/upload-artifact@v4
        with:
          name: linux_x86_64-binary
          path: raylean_linux-x86_64.tar.gz
          if-no-files-found: error
